// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsG_4m0a_g3CFNCeExdk5q-TSXEDdmog8',
    appId: '1:409202831712:web:9d14ab7991afab8d5cae05',
    messagingSenderId: '409202831712',
    projectId: 'heart-daejeon',
    authDomain: 'heart-daejeon.firebaseapp.com',
    storageBucket: 'heart-daejeon.firebasestorage.app',
    measurementId: 'G-300V0QYS5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEAh9U6Db4ogduNiAt2l5TK4bIexuJKcE',
    appId: '1:409202831712:android:124b0a06556e997e5cae05',
    messagingSenderId: '409202831712',
    projectId: 'heart-daejeon',
    storageBucket: 'heart-daejeon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTSUzQDouizR85T0yNzJWjEYviNtjXbxY',
    appId: '1:409202831712:ios:176af05c4f1ddcf05cae05',
    messagingSenderId: '409202831712',
    projectId: 'heart-daejeon',
    storageBucket: 'heart-daejeon.firebasestorage.app',
    iosBundleId: 'com.example.testver2Heart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTSUzQDouizR85T0yNzJWjEYviNtjXbxY',
    appId: '1:409202831712:ios:176af05c4f1ddcf05cae05',
    messagingSenderId: '409202831712',
    projectId: 'heart-daejeon',
    storageBucket: 'heart-daejeon.firebasestorage.app',
    iosBundleId: 'com.example.testver2Heart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsG_4m0a_g3CFNCeExdk5q-TSXEDdmog8',
    appId: '1:409202831712:web:c9425ab878eb913a5cae05',
    messagingSenderId: '409202831712',
    projectId: 'heart-daejeon',
    authDomain: 'heart-daejeon.firebaseapp.com',
    storageBucket: 'heart-daejeon.firebasestorage.app',
    measurementId: 'G-SN482LVET0',
  );
}
